require 'minitest/spec'
require 'minitest/autorun'

require 'jekyll'
require_relative '../lib/jekyll-paginate-v2/version'
require_relative '../lib/jekyll-paginate-v2/generator/defaults'
require_relative '../lib/jekyll-paginate-v2/generator/utils'
require_relative '../lib/jekyll-paginate-v2/generator/compatibilityUtils'
require_relative '../lib/jekyll-paginate-v2/generator/paginationIndexer'
require_relative '../lib/jekyll-paginate-v2/generator/paginator'
require_relative '../lib/jekyll-paginate-v2/generator/paginationPage'
require_relative '../lib/jekyll-paginate-v2/generator/paginationModel'
require_relative '../lib/jekyll-paginate-v2/generator/paginationGenerator'