version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    resource_class: gpu.medium
    steps:
      - checkout
      - run:
          name: Setup CI environment
          command: ./scripts/setup_ci.sh
      - run:
          name: Install Deps
          command: ./scripts/install.sh
      - run:
          name: Sanity Check
          command: . ~/miniconda3/etc/profile.d/conda.sh; conda activate base; python scripts/sanity_check.py
      - run:
          name: Run Pytorch scripts
          command: ./scripts/run_pytorch.sh
          no_output_timeout: 1h

workflows:
  version: 2
  workflow-build:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
