name: Run TorchHub

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && format('ci-master-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  torchub-job:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: linux.g5.4xlarge.nvidia.gpu
      repository: pytorch/hub
      gpu-arch-type: cuda
      gpu-arch-version: 11.6
      timeout: 90
      script: |
        # Mark Build Directory Safe
        git config --global --add safe.directory /__w/hub/hub

        set -euxo pipefail
        
        ## Install Deps
        ./scripts/install_conda.sh
        ./scripts/install_deps.sh

        ## Sanity Check
        . ~/miniconda3/etc/profile.d/conda.sh
        conda activate base
        python scripts/sanity_check.py

        ## Run Pytorch scripts
        ./scripts/run_pytorch.sh
